apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.port }}

        volumeMounts:
          - name: storage
            mountPath: {{ .Values.persistence.mountPath }}
          - name: {{ .Values.provisioning.datasources.configMapName }}
            mountPath: {{ .Values.provisioning.datasources.mountPath }}
          - name: {{ .Values.provisioning.dashboards.configMapName }}
            mountPath: {{ .Values.provisioning.dashboards.mountPath }}
          - name: {{ .Values.provisioning.dashboardFiles.configMapName }}
            mountPath: {{ .Values.provisioning.dashboardFiles.mountPath }}

      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ .Values.appName }}
        - name: {{ .Values.provisioning.datasources.configMapName }}
          configMap:
            name: {{ .Values.provisioning.datasources.configMapName }}
        - name: {{ .Values.provisioning.dashboards.configMapName }}
          configMap:
            name: {{ .Values.provisioning.dashboards.configMapName }}
        - name: {{ .Values.provisioning.dashboardFiles.configMapName }}
          configMap:
            name: {{ .Values.provisioning.dashboardFiles.configMapName }}