apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volumes.nginxImageStorage.pvcName }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.volumes.nginxImageStorage.space }}
  storageClassName: standard