apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.port.ui}}
            - containerPort: {{ .Values.port.colelctor}}
            - containerPort: {{ .Values.port.otlp}}
          envFrom:
          - configMapRef:
              name: {{ .Values.appName }}

          volumeMounts:
            - name: badger-storage
              mountPath: {{ .Values.volumes.dbStorage.path }}
      volumes:
        - name: badger-storage
          persistentVolumeClaim:
            claimName: {{ .Values.appName }}