appName: reservation-service
namespace: default
replicas: 1
image:
  name: magley/bookem-reservation-service
  tag: "nightly-0.1.0"
port: "8080"

configmap:
  data:
    DB_HOST: reservation-db
    DB_PORT: 5432
    DB_NAME: bookem_reservationdb_db
    DB_USER: bookem_reservationdb_user
    DB_PASSWORD: password123
    JWT_PUBLIC_KEY_PATH: /app/keys/public_key.pem