{
 "title": "Web Traffic",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Unique visitors",
   "type": "stat",
   "description": "Unique IPs + User Agents",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count( sum by (service_name, client_ip, user_agent) ( count_over_time({service_name!=\"\"} | json | client_ip != \"\" [5m]) ) ) by (service_name)"
    }
   ]
  },
  {
   "title": "HTTP 4XX and 5XX in the last 24h",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (increase(http_requests_total{status=~\"4..|5..\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests in the last 24h",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (increase(http_requests_total[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 2XX and 3XX in the last 24h",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (increase(http_requests_total{status=~\"2..|3..\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 4XX and 5XX (all time)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (http_requests_total{status=~\"4..|5..\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 404 (Last 24h)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (http_requests_total{status=~\"404\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 2XX and 3XX (all time)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (http_requests_total{status=~\"2..|3..\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 404 (all time)",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job, endpoint) (http_requests_total{status=\"404\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic size (GB)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum by (job) (http_response_size_bytes / 1024 / 1024 / 1024)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}