appName: web-app
namespace: default
replicas: 1
image:
  name: magley/bookem-web-app
  tag: "0.9.0"
port: "80"
publicPort: 30000

configmap:
  js_env_path: /usr/share/nginx/html/env.js
  js_env_file: env.js
  data:
    USER_SERVICE_URL: http://api.bookem.local/user
    ROOM_SERVICE_URL: http://api.bookem.local/room
    ROOM_SERVICE_IMAGES_URL: http://api.bookem.local/images
    RESERVATION_SERVICE_URL: http://api.bookem.local/reservation
    NOTIFICATION_SERVICE_URL: http://api.bookem.local/notification
    RATING_SERVICE_URL: http://api.bookem.local/rating