apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.appName }}-jwt-keys"
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  public_key.pem: {{ .Files.Get "secrets/keys/public_key.pem" | b64enc }}