apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-db
  namespace: default
  labels:
    app: user-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-db
  template:
    metadata:
      labels:
        app: user-db
    spec:
      containers:
      - name: user-db
        image: postgres:15.9-alpine3.20
        ports:
        - containerPort: 5432

        envFrom:
        - configMapRef:
            name: user-db

        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-storage

      volumes:
      - name: db-storage
        persistentVolumeClaim:
          claimName: user-db