apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-db
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard