apiVersion: v1
kind: Service
metadata:
  name: user-db
  namespace: default
  labels:
    app: user-db
spec:
  selector:
    app: user-db
  ports:
    - protocol: TCP
      targetPort: 5432
      port: 5432