apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
data:
  DB_HOST: {{ .Values.configmap.data.DB_HOST | quote }}
  DB_PORT: {{ .Values.configmap.data.DB_PORT | quote }}
  DB_NAME: {{ .Values.configmap.data.DB_NAME | quote }}
  DB_USER: {{ .Values.configmap.data.DB_USER | quote }}
  DB_PASSWORD: {{ .Values.configmap.data.DB_PASSWORD | quote }}
  JWT_PUBLIC_KEY_PATH: {{ .Values.configmap.data.JWT_PUBLIC_KEY_PATH | quote }}